package io.github.lattesyobon.audio;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo {
    public static void loadInfo(ModMetadata meta) {
        meta.modId = AudioMod.MODID;
        meta.name = AudioMod.NAME;
        meta.description ="Mod to play music or add instruments";
        meta.version = AudioMod.VERSION ;
        meta.url = "https://github.com/LatteSyobon/audiomod";
        meta.authorList.add("LatteSyobon");
        meta.credits = "";
        meta.logoFile ="assets/aluminiummod/logo.png";
        meta.autogenerated = false;
    }
}
